<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'id' => 'formGuardar',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<input type="hidden" name="campo" id="campo" value='1' />    
<?php echo $this->form()->closeTag() ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<?php 
$this->th3 = "Banco : ".$this->empleado;
echo $this->render('layout/h3rojo') ?>

<div class="row">    
<div class="col-sm-4">Banco asociado:<br />
<?php
    $select = $form->get('tipo')->setAttribute("id","tipo");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<div class="col-sm-3">Codigo de transito alterno:<br />    
<?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
 </div> 
  <div class="col-sm-2">
    <?php echo $this->formElement($form->get('guardar')) ?>
  </div>
</div>
<hr />
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<input type="hidden" name="campo" id="campo" value='2' />
<?php echo $this->form()->closeTag() ?>

<div id="resultado"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ 
        $id=$dato["id"];
        ?>
        <tr>
            <td><?php echo $dato["id"] ?></td>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["codBanco"] ?></td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php         
$this->ncol='null,null,';
echo $this->render('layout/tabla_tb') ?>        
        
<?php
//$this->lin= $id ;
echo $this->render('layout/iregresar') ?> 
<script>
// Moficicacion en registro de novedades 
function editarN(id){  
   var dev = $("#dev_"+id).val();
        var parametros = {
            "id"   : id,
            "dev"  : dev
        };

        $.ajax({
           data:  parametros,     
           type:  'post',
           url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>inov',
           beforeSend: function () {
              $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Recalculando por favor espere...');
             },
           success:  function (response) {
              $("#resultado").html(response);                    
             }
        }); // Fin ajax        
};

$( "#formGuardar" ).submit(function( event ) {
  var val = $("#tipo").val();
  if (val == '')
  {
    alert('Seleccione el banco ')
    event.preventDefault();
  }    

  
});
</script>