<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'method' => 'post',
    'id' => 'formGuardar',
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php    
    $name = $form->get('id'); // id de la matriz 
    echo $this->formInput($name);    
?>
<?php    
    $name = $form->get('id2'); // Tipo de matriz
    echo $this->formInput($name);    
?>
 
<div class="row">    
  <div class="col-sm-5">Empleado:<br />
      <?php
      $select = $form->get('idEmp')->setAttribute("id","idEmp");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
      <div id='resultadoD'></div><!-- Datos del cargo -->            
  </div>
      <div class="col-sm-5"><br />
        <div id='resultadoP'></div><!-- Datos del proyecto -->      
      </div>               
  <?php
  ////// TIPO LINEAL //////
  if ($this->tipo>0)
  {  ?>           
     <div class="col-sm-4">Concepto:<br />
      <?php
        $select = $form->get('tipo')->setAttribute("id","tipo");
        echo $this->formSelect($select);
        echo $this->formElementErrors($select);       
      ?>
     </div>
     <div id="resultado"></div>
    </div>
    <br />
    <div class="row">         
     <div class="col-sm-3">Afectar en el periodo:<br />
     <i class="fa fa-calendar green bigger-90"></i>
       <?php
         $select = $form->get('idCal');
        echo $this->formSelect($select);
        echo $this->formElementErrors($select);
       ?>   
      </div>                 
      <div class="col-sm-2">Ejecutado el:<br />
       <?php
         $name = $form->get('fechaIni');
         echo $this->formInput($name);
         echo $this->formElementErrors($name);?>
      </div>

      <div class="col-sm-2">Distribuir en cuotas de  :<br />
       <?php
         $name = $form->get('numero');
         echo $this->formInput($name);
         echo $this->formElementErrors($name);?>
      </div>

<hr />    
<?php echo $this->formElement($form->get('agregarnov')->setAttribute("id","agregar") ) ?>
  <?php } ?>      

<hr />
<?php
  ////// TIPO MATRIZ //////
  if ($this->tipo==0) 
{ ?>

<hr />

<table class="table table-striped table-bordered">
 <thead>
   <tr>
<?php foreach ($this->datos as $dato){ ?>
     <th><?php echo $dato['alias']; ?></th>
<?php } ?>
     <th>Periodo</th>
     <th></th>
   </tr>
  </thead>           
  <tr>
<?php foreach ($this->datos as $dato){ ?>  
  <td><div class="col-sm-10">
      <?php
    $name = $form->get('valorM')->setAttribute('id','val'.$dato['id'])
                 ->setAttribute('value','')
                 ->setAttribute('class','col-sm-10')
                 ->setAttribute('name','val'.$dato['idConc']);
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
    $name = $form->get('id2')->setAttribute('id','conc'.$dato['id'])
                 ->setAttribute('value',$dato['idConc'])
    ->setAttribute('name','conc'.$dato['idConc']);
    echo $this->formInput($name);    
    ?></div>      
  </td>  
<?php } ?> 
  <td>
<?php
    $select = $form->get('idCal')->setAttribute('class','col-sm-14');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>      
         </br>Ejecutado el:<br />
         <?php
            $name = $form->get('fechaIni');
            echo $this->formInput($name);
           echo $this->formElementErrors($name);?>
  </td>
  </td>
   <td>
       <?php echo $this->formElement($form->get('agregarnov')->setAttribute("id","agregar") ) ?>       
   </td>
  </tr>     
</table>
<?php } ?>
 <?php 
 $con = '';
 if ( $datNovA['num'] > 0 )
      $con = '(Actualmente hay una nomina activa, verifique el periodo ha afectar)';
 $this->th3='Novedades de empleados '.$con;
 echo $this->render('layout/h3rojo') ?>



<?php echo $this->form()->closeTag() ?>


<!-- LISTADO DE NOVEDADES EN CUSRO -->
<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datNov as $dato){ ?>
        <tr>
            <td><?php echo $dato["CedEmp"] ?></td>                        
            <td><?php echo $dato["nomEmp"].' '.$dato["apeEmp"] ?></td>            
            <td><?php echo $dato["nomConc"] ?></td>
            <td><?php echo number_format($dato["sueldo"]) ?></td>                                    
            <td><?php echo $dato["horas"] ?></td>                                    
            <td><?php echo number_format($dato["devengado"],0) ?>
            <?php // Cuotas en devengado
             if ( $dato["devengado"] >0 )
             {
                if ( $dato["cuotas"]>0 )
                {
                   echo $this->render('layout/icalendar');
                   echo '<h5 class="bigger-110 orange">('.$dato["cuotas"].' cuotas de '.number_format($dato["devengado"]/$dato["cuotas"]).')</h5>';
                }
             }  
            ?>  
            </td>                        
            <td><?php echo number_format($dato["deducido"],0) ?>
            <br />
            <?php // Cuotas en dedcido
             if ( $dato["deducido"] >0 )
             {
                if ( $dato["cuotas"]>0 )
                {
                   echo $this->render('layout/icalendar');
                   echo '<h5 class="bigger-110 orange">('.$dato["cuotas"].' cuotas de '.number_format($dato["deducido"]/$dato["cuotas"]).')</h5>';
                }
             }  
            ?>  
            </td>                        
            <td><?php echo $dato["fechaI"].' - '.$dato["fechaF"] ?>
            <br />
            <?php // Informacion del proyecto
                if ( $dato["idProy"]>1 )
                {
                   echo $this->render('layout/iproyecto');
                   echo '<h5 class="bigger-110 orange">'.$dato["nomProy"].'</h5>';
                }
             ?>  
            </td>                                    
            <td><?php if ($dato["fechaEje"] != '0000-00-00') echo $dato["fechaEje"]; else echo 'Indefinido';  ?>
            </td>                       

            <td>
                <a href="<?php echo $this->basePath() ?><?php $this->idEli = $dato["id"]; echo $this->lin?>d/<?php echo $dato["id"]?>"> 
                    <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Principal\Model\AlbumTable($con)';// Modelo de consulta
$this->funcion   = '$m->getDnovedades( '."''".')';
$this->columnas  = "CEDULA, NOMBRES, APELLIDOS, CONCEPTO,SUELDO, HORAS, DEVENGADO, DEDUCIDO, FECHA , FECHA ";// Columnas
$this->datos     = "CedEmp,nomEmp,apeEmp,nomConc,sueldo,horas,devengado,deducido,fechaI,fechaF";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/tabla_p') ?> 
   
<?php 
$this->ncol='null,null,null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>   

<?php echo $this->render('layout/iregresar') ?>    

<script>    
$( "#formGuardar" ).submit(function( event ) {
   var tipo  = $("#tipo").val(); // conceptos de cotizaciones     
   if (tipo == '')
   {
       alert('Seleccione el concepto');
       event.preventDefault();
   }
   var tipo  = $("#idEmp").val(); // id empleados
   if (tipo == '')
   {
       alert('Seleccione el empleado');
       event.preventDefault();
   }   
   if ($('#numero').length){
      var tipo  = $("#numero").val(); // 
      if (tipo == '')
      {
         alert('Digite el valor');
         event.preventDefault();
      }   
   }
        $('#agregar').attr('disabled', 'disabled');
        return true;      
});
// Guardar material adicional
$("#tipo").change(function () {    
 var id  = $("#tipo").val(); // id Cotizacion      
 
 var parametros = {
      "id"    : id,
  };  
  $.ajax({
    data:  parametros, 
    url:  '<?php echo $this->basePath() ?><?php echo $this->lin?>av',
    type: 'post',
    beforeSend: function () {
        $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
    },
    success: function (response) {   
        $("#resultado").html(response); 
    }
  }); // Fin  agregar nuevo componente al sistema                             

}); 

    $('#idEmp').change(function(){    
        var id = $("#idEmp").val();
        var parametros = {
               "idEmp" : id,
            };  
        // Datos del cargo    
        $.ajax({
            data:  parametros,     
            url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>e',
            type:  'post',
            beforeSend: function () {
                $('#resultadoD').html('<option value="">Cargando...</option>')                
               },
            success:  function (response) {
                $('#resultadoD').html(response);
            }
        });                        
        // Datos del proyecto
        $.ajax({
            data:  parametros,     
            url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>cp',
            type:  'post',
            beforeSend: function () {
                $('#resultadoP').html('<option value="">Cargando...</option>')                
               },
            success:  function (response) {
                $('#resultadoP').html(response);
            }
        });                        

    });        
     
</script> 
    
