<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
  <div class="col-sm-4">Tipo de nómina:<br />              
<?php
    $select = $form->get('tipo');
    $select->setAttribute('id', 'tipo');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
  </div> 
</div>
<hr />
<div class="row">      
  <div class="col-sm-4" id='grupos' >Grupo de nómina:<br />
  <?php
    $select = $form->get('idGrupo')->setAttribute("id","idGrupo")->setAttribute("name","idGrupo");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
  ?>
  </div>    
  <!-- TIPOS DE NOMINA LIQUIDACION -->
  <div class="col-sm-4" id='empleados' >Empleados:<br />
    <?php
    $select = $form->get('idEmp')->setAttribute("id","idEmp");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
    ?>
  </div>    
  <div class="col-sm-4" id='empleados' >Fecha de corte:<br />
   <?php
     $name = $form->get('fechaIni')->setAttribute("id","fechaIni");;
     echo $this->formInput($name);
     echo $this->formElementErrors($name);
   ?>
  </div>    

</div>    
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    


<script>
$(function () 
{
  $("#idEmpM").hide();
  $("#fechaIni").hide(); 

  $("#tipo").change(function (){  // Validacion segun el tipo de nomina
  	var nombre =  $("#tipo option:selected").text();
	  var lon = nombre.length;
	  var tipo = nombre.substr(lon-2, 1) ;
//	alert(tipo)
    if (tipo==0)// Nomina normal	
	  {
	     $("#grupos").show();
	     $("#idEmpM").val('');
		   $("#empleados").hide();
       $("#fechaIni").hide(); 
    }
    if (tipo==4)// Liquidacion de empleado	
	  {
	     $("#empleados").show();
	     $("#idGrupo").val('');
		   $("#grupos").hide();
       $("#fechaIni").show(); 
    }
	
   });// Generacion de nomina
 })

</script>
