<?php echo $this->render('layout/titulo') ?>


<?php
$form = $this->form;
$form->prepare();
?>

<?php
$form->setAttributes(array(
    'action' => $this->url.$this->lin,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">
  <div class="col-sm-4">Buscar por codigo o nombre:<br />              
   <?php
    $name = $form->get('cedula');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
   ?>
  </div>
  <div class="col-sm-2"><br />              
    <?php echo $this->formElement($form->get('buscar')) ?>
  </div>
</div>  

<?php echo $this->form()->closeTag() ?>    
<hr />
<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["codigo"] ?></td>            
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["paux"] ?></td>            
            <td><?php echo $dato["pgas"] ?></td>                        
            <td><?php echo $dato["pccos"] ?></td>                        
            <td><?php echo $dato["pter"] ?></td>                                    
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
   
<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Nomina\Model\Entity\Bancos($con)';// Modelo de consulta
$this->funcion   = '$m->getRegistro()';
$this->columnas  = "CODIGO, BANCO";// Columnas
$this->datos     = "id, nombre";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/tabla_p') ?>        
<?php 
$this->ncol='null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        