<style type="text/css">
#ejemplo{
     overflow:scroll;
     height:200px;
     width:550px;
}
</style>
<div id="ejemplo">
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Puesto</th>        
        <th>Ciudad</th>                
        <th>Proyecto</th>          
        <th>Ok</th>          
    </tr>    
<?php foreach( $this->datos as $dat ){ ?>
  <tr>
    <td><?php echo $dat['nombre']; ?></td>      
    <td><?php echo $dat['nomCiu']; ?></td>  
    <td><?php echo $dat['nomProy']; ?></td>   
    <td>

        <a href="javascript:editarR(<?php echo $dat["id"]?>)"> <?php echo $this->render('layout/iok') ?> </a>  

    </td>                
  <tr>        
<?php } ?>
</table>  
</div>

<script>    

// Material adicional
function matAdiE(id)
{        
  var idPord  = $("#id").val(); // id Cotizacion      
  var parametros = {
      "tipo"  : 2,   
      "idE"   : id,
      "id"    : idPord, 
  };  
  $.ajax({
    data:  parametros, 
    url:  '<?php echo $this->basePath() ?><?php echo $this->lin?>adi',
    type: 'post',
    beforeSend: function () {
        $("#resultadoMa").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
    },
    success: function (response) {   
        $("#resultadoMa").html(response); 
    }
  }); // Fin  agregar nuevo componente al sistema                                 
}  
</script>  
