<?php
$form = $this->form;
$form->prepare();
?>


<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<?php
$form->setAttributes(array(
    'action' => $this->url.$this->lin.'gf',
    'method' => 'post',
    'id'     => 'formGuaradarF'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);

    $name = $form->get('id');
    echo $this->formInput($name);    
?>            
<br />    
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-3">Nombres:<br />              
<?php
    $name = $form->get('nombre2');

    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
  <div class="col-sm-3">Apellidos:<br />                  
<?php
    $name = $form->get('apellido2');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
  </div>
  <div class="col-sm-2">Parentesco:<br />              
<?php
    $select = $form->get('parentesco');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>          
</div>
</div>
    <hr />    
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-3">Sexo:<br />              
<?php
    $select = $form->get('sexo2')->setAttribute("class","sexo");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-3">Fecha de nacimiento:<br />              
<?php
    $name = $form->get('fechaIni');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>        
  </div>
  <div class="col-sm-3">Nivel de estudio:<br />                
  <?php
    $select = $form->get('idNest')->setAttribute("class","sexo");;
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>       
  </div>    
</div>
<hr />
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-3">Usa lentes ?:<br />              
<?php
    $select = $form->get('lentes2');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>
  </div>
</div>  
<hr />
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-4">Institución donde esta estudiando:<br />              
<?php 
    echo ($this->formRow($form->get('instituto') ));
?>                                           
  </div>
</div>   
<hr />
<div class="row">    
  <div class="col-sm-1"></div>                  
  <div class="col-sm-4">Cuenta con alguna limitación fisica ?:<br />              
<?php 
    echo ($this->formRow($form->get('limitacion2') ));
?>    
                                                   
<?php echo $this->form()->closeTag() ?>    
</div>
</div>