<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i/'.$this->id,
    'method' => 'post',
    'id' => 'formGuardar',
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php    
    $name = $form->get('id'); // id de la matriz 
    echo $this->formInput($name);    
?>

<div class="row">    
  <div class="col-sm-5">Concepto:<br />
      <?php
      $select = $form->get('idConc')->setAttribute("id","idConc");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>     
  <div class="col-sm-2">Valor:<br />
  <?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
  ?>
  </div>    
</div>
<hr />
$diasDiurno - $diasNocturno - $diasFestivo <br />
$dia31 - $descansos - <br />
$dias (Dias trabajados) - $diasF (Dias festivos trabajados) - <br />
$nocturnos (Nocturnos trabajados) - $nocturnosF(Nocturnos festivos) - <br />
$domingos (Domingos trabajados) - $domingosC (Domingos descansos) - $domingosF (Domingos festivos) -  
<hr />
<div class="row">    
  <div class="col-sm-4">
    <?php echo ($this->formRow($form->get('formula')));?>
  </div>  
   <div class="col-sm-2"><br />
     <?php echo $this->formElement($form->get('registrar')) ?>
   </div>  
</div>


<?php echo $this->form()->closeTag() ?>
<hr />

<div id="resultado"></div>
<!-- LISTADO DE EMPLEADOS EN CURSO -->
<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["id"]; ?></td>                       
            <td><?php echo $dato["nombre"] ?></td>
            <td>      <?php 
         echo ($this->formRow($form->get('comenN')->setAttribute("class","span13")
                                                  ->setAttribute("id", "comen".$dato["id"]) 
                                                  ->setAttribute("value", $dato["formula"] )

                                                  )); 
      ?>        

            </td>
            <td>
             <div class="col-sm-6"><br />
               <?php echo ($this->formRow($form->get('validacion')
                                               ->setAttribute("id", "valida".$dato["id"])->setAttribute("value", $dato["valida"] )

                                                ));?>
<div class="row">    
  <div class="col-sm-6"><br />
    <?php echo ($this->formRow($form->get('si')
                     ->setAttribute("id", "si".$dato["id"])
                     ->setAttribute("value", $dato["si"] )));?>
  </div>  
</div>  

<div class="row">    
  <div class="col-sm-6"><br />
    <?php echo ($this->formRow($form->get('no')
                                    ->setAttribute("id", "no".$dato["id"])
                                    ->setAttribute("value", $dato["no"] )));?>
  </div>  
</div>               
             </div>  
            </td>
            <td><?php           
               echo ($this->formRow($form->get('horaG')
                                   ->setAttribute("value", $dato["horas"] )
                                   ->setAttribute("id", "horas".$dato["id"]) )); 
            ?></td>                                  
            <td><?php
               echo ($this->formRow($form->get('horaG')
                                   ->setAttribute("value", $dato["horasFijas"] )
                                   ->setAttribute("id", "horasFijas".$dato["id"]) ));              
            ?>
            </td> 
            <td>
                 <a href="javascript:editarN(<?php echo $dato["id"]; ?>);" class="blue" id="nov"><?php echo $this->render('layout/iok') ?>
                 </a>
            </td>                   
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> 
                    <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php
echo $this->render('layout/tabla_p') ?>  

<?php echo $this->render('layout/iregresar') ?>    

<script>    
// Moficicacion en registro de novedades 
function editarN(id){  
   var horasF = $("#horasFijas"+id).val(); 
   var horas = $("#horas"+id).val(); 
   var formula = $("#comen"+id).val(); 
   var valida = $("#valida"+id).val(); 
   var si = $("#si"+id).val(); 
   var no = $("#no"+id).val(); 

   var parametros = {
       "id"     : id,       
       "horasFijas" : horasF,
       "horas" : horas,
       "formula" : formula,
       "valida" : valida,
       "si" : si,
       "no" : no,                     
   }; 
   $.ajax({
           data:  parametros,     
           type:  'post',
           url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>pg',
           beforeSend: function () {
              $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Actualizando por favor espere...');
             },
           success:  function (response) {
              $("#resultado").html(response);                    
             }
   }); // Fin ajax        
};

// VALIDACIONES 
$( "#formGuardar" ).submit(function( event ) {
   var tipo  = $("#tipo").val(); // conceptos de cotizaciones     
   if (tipo == '')
   {
       alert('Seleccione el concepto');
       event.preventDefault();
   }
   var tipo  = $("#idEmp").val(); // id empleados
   if (tipo == '')
   {
       alert('Seleccione el empleado');
       event.preventDefault();
   }   
   if ($('#numero').length){
      var tipo  = $("#numero").val(); // 
      if (tipo == '')
      {
         alert('Digite el valor');
         event.preventDefault();
      }   
   }   
});     
</script> 
    
<?php 
$this->ncol='null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>   


