<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post',
    'id'     => "formGuaradar"
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">
<div class="col-sm-4">Empleado:<br />
  <?php
    $select = $form->get('idEmp')->setAttribute("id", "idEmp");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
  ?>
</div> 
<div class="col-sm-2">Estado del documento:<br />        
<?php
       $select = $form->get('estado');
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
?>        
</div>
</div>
<hr />
<!-- DATOS EL SUELDO Y CARGO DEL EMPLEADO-->
<div class="row">
  <div class="col-sm-4">
     <div id='resultado'></div>
  </div> 
</div>
<br />
<div class="row">
<div class="col-sm-2">Inicia desde el:<br />
<?php
    $name = $form->get('fechaIni');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);?>
</div> 
<?php if ( $this->escala==1 ) {?>
<div class="col-sm-4">Sueldo por escala :<br />        
<?php
       $select = $form->get('idSalario');
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
?>        
</div> 
<?php }else{?>
<div class="col-sm-4">Sueldo nuevo :<br />        
<?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>        
</div> 
<?php } ?>
</div>
<hr />
<div class="control-group">
    <?php echo ($this->formRow($form->get('comen'))); ?>
</div>  

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    
    
<script>      
$(function (){    
    $('#idEmp').change(function(){    
        var id = $("#idEmp").val();
        var parametros = {
               "idEmp" : id,
            };  
        $.ajax({
            data:  parametros,     
            url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>e',
            type:  'post',
            beforeSend: function () {
                $('#resultado').html('<option value="">Cargando...</option>')                
               },
            success:  function (response) {
                $('#resultado').html(response);
            }
        });                        
    });        

})
</script>

