<?php echo $this->render('layout/titulo') ?>

<?php

$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'id'     => 'formGuaradar',    
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="tabbable">
  <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
  <li class="active">
      <a data-toggle="tab" href="#datos">Datos basicos</a>
  </li>
  <li>
      <a data-toggle="tab" href="#confiGen">Configuración general</a>
  </li>


  <li>
     <a data-toggle="tab" href="#confiCon">Configuración contable</a>
  </li>
   <li>
     <a data-toggle="tab" href="#conProcesos">Procesos</a>
  </li>
  </ul>

  <div class="tab-content"> 
      
      <div id="datos" class="tab-pane in active"><!-- DATOS BASICOS -->             
          <br />
<div class="row">
<div class="col-sm-4">
<?php
    $name = $form->get('nombre')
                 ->setAttribute('id','nombre')
                 ->setAttribute("class", "col-sm-9");
    echo $formLabel->openTag()."Nombre del concepto:";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div> 
<div class="col-sm-4">
<?php
    $name = $form->get('alias');
    echo $formLabel->openTag().'Alias del concepto:';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div> 
<div class="col-sm-4">
<?php
    $name = $form->get('codigo');
    echo $formLabel->openTag().$name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div> 
</div>
<hr />
<div class="row">
   
<div class="col-sm-4">
<?php
    $select = $form->get('tipo')->setAttribute('id','tipo');
    echo $formLabel->openTag().'Tipo de concepto';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
<div class="col-sm-4">
<?php
    $select = $form->get('tipo2')->setAttribute('id','tipo2');
    echo $formLabel->openTag().'Valor del concepto';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 

 <div class="col-sm-4">Estado del concepto:<br />                      
      <?php
       $select = $form->get('estado');
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
       ?>
  </div>
</div>
<hr />
<div class="row">
<div class="col-sm-3">
<?php
    $select = $form->get('check1');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Automático  
</div> 
<div class="col-sm-3">
<?php
    $select = $form->get('check2');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Informativo
</div>     
<div class="col-sm-3">
<?php
    $select = $form->get('check4');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Concepto de tercero
</div>     
<div class="col-sm-3">
<?php
    $select = $form->get('check5');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Concepto de convención
</div>     

</div>
</div><!-- FIN DATOS BASICOS -->

 <div id="conProcesos" class="tab-pane in active">
   <!-- PROCESOS DEL CONCEPTO -->
<h3 class="header smaller lighter blue">Procesos</h3>
<?php 
foreach ($this->datos as $dato){ ?>
<div class="form_element">
<?php
    $i = $dato['id'];
    $select = $formn->get('checki'.$i); // Marcacion de cada proceso
    echo $this->formCheckbox($select);
?><span class="lbl"></span><?php echo $dato['nombre'].' '; ?>
<?php 
    $name = $formn->get('idi'.$i)->setAttribute("value",$dato['id']); // Se usa id escondigo por cada check para id del proceso.
    echo $this->formInput($name);       

echo '</div>';
} ?>

 
 </div>
<div id="confiGen" class="tab-pane in active"><!-- CONFIG GENERAL -->                 

<div class="row">    
<!--<div id="resultado" ></div>-->
<div class="col-sm-4">
    <?php
      $select = $form->get('idTnomm')->setAttribute('id','idTnomm');
      echo $formLabel->openTag().' nominas afectadas';
      echo $formLabel->closeTag();
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>
<div class="col-sm-4">    
   <?php $select = $form->get('periodo');
    echo $formLabel->openTag().'Periodo de ejecución ';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);?>   
  </div>         
  <div class="col-sm-4">    
   <?php $select = $form->get('tipo4');
    echo $formLabel->openTag().'Concepto retro activo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);?>   
  </div>         

</div>        
<br />
<div class="row">
<div class="col-sm-4">
    <?php
      $select = $form->get('idConcM');
      echo $formLabel->openTag().' Concepto hijos';
      echo $formLabel->closeTag();
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>     
<div class="col-sm-4">
    <?php
    $select = $form->get('idTempM');
    echo $formLabel->openTag().'Afecta solo los tipo de empleados a continuación';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>    
<div class="col-sm-4">
<?php
    $select = $form->get('idFor');
    echo $formLabel->openTag().'Formula asociada';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
</div>
<hr />
<div class="row">
  <div class="col-sm-4">    
   <?php $select = $form->get('tipo5');
    echo $formLabel->openTag().'Concepto de cruze ';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);?>   
  </div>  
</div>
</div><!-- FIN CONFIG GENERAL -->                 

<div id="confiCon" class="tab-pane in active"><!-- CONFIG CONTABLE -->                 
<div class="row">    
  <div class="col-sm-4">Codigo de cuenta:<br />                      
  <?php
    $select = $form->get('codCta')->setAttribute('id','codCta');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
  ?>    
  </div>
  <div class="col-sm-4">Naturaleza de cuenta:<br />                      
  <?php
    $select = $form->get('natCta');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
  ?>    
  </div>    
</div>    
<hr />
<div class="row">    
  <div class="col-sm-4">Tercero pre asignado:<br />                      
  <?php
    $select = $form->get('idTer');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
  ?>    
  </div>
<div class="col-sm-4">

<div class="col-sm-6">Traer nit de fondos:<br />                      
      <?php
       $select = $form->get('condFis')->setAttribute("class","idNitFondos");
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
       ?>
  </div>
 

</div>  
<div  id='idTomFon'  class="col-sm-4">
<?php
    $select = $form->get('tipo3')
                              ->setAttribute('id','idTomFon2')
                                ->setAttribute('class','idTomFon');
                              //->setAttribute("disabled", true);
    echo $formLabel->openTag().'Tomar fondo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
<div id='resultado'></div>   
</div>    
<hr />


<?php 
// configuracion de cuentas en prefijos fijos 
?>
<div id='resultadoP'></div>
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>id</th>
    <th>Prefijo</th>
    <th>Cuenta</th>        
    <th>..</th>    
  </tr>
 </thead>
    <?php
     foreach ($this->datPref as $dato){ ?>    
        <tr>
            <td><?php echo $dato["id"] ?></td>                                    
            <td><?php echo $dato["nombre"] ?></td>
            <td>
             <?php
               $select = $form->get('tipoC')
                              ->setAttribute('id','codCtaPref'.$dato["id"])
                              ->setAttribute('value',$dato["codCta"] );
                 echo $this->formSelect($select);
                 echo $this->formElementErrors($select);                       
             ?>
            </td>
            <td>
                 <a href="javascript:editarN(<?php echo $dato["id"]; ?>);" class="blue" id="nov"><?php echo $this->render('layout/iok') ?>
                 </a>

            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
</div><!-- CONFIG CONTABLE -->                 

</div>

<script>

//  $



 $(document).ready(function()
   {
     
      var  valor =  $('.idNitFondos').val();
       //alert('ddd'); 
     
      
       
        if(valor==1)
        {

          $("#idTomFon").show();
          
         
        }
        else
        {
          
            $("#idTomFon").hide();
        }
     
     //
     $('.idNitFondos').on('change', function()
     {
        
      var  valor =  $('.idNitFondos').val();
       //alert('ddd'); 
      if(valor==1)
        {

          $("#idTomFon").show();
          
         
        }
        else
        {
          
            $("#idTomFon").hide();
        }

     });

    

    });
// Moficicacion en prefijos 
function editarN(idPref){  
   var id = $("#id").val(); 
   var valor = $("#codCtaPref"+idPref).val(); 
   var parametros = {
       "id"     : id,       
       "idPref" : idPref,       
       "valor"  : valor,
   }; 
   $.ajax({
           data:  parametros,     
           type:  'post',
           url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>pg',
           beforeSend: function () {
              $("#resultadoP").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Actualizando por favor espere...');
             },
           success:  function (response) {
              $("#resultadoP").html(response);                    
             }
   }); // Fin ajax        
};
</script>

<hr />
<script>
$(function () {
  $("#check").click(function () {
   $.ajax({
       success:  function (response) 
       {
         if($("#check").is(':checked')) 
         {
           $("#resultado").show(); 
         }else{ 
           $("#resultado").hide(); 
         }                 
       }
     });           
   })
  })

         if($("#check").is(':checked')) 
         {
           $("#resultado").show(); 
         }else{ 
           $("#resultado").hide(); }
</script>

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    



<script>
  $(function() {
    // Validar guardad de empleados
    $( "#formGuaradar" ).submit(function( event ) 
    {
       if ( $("#nombre").val()==0)
       {
         alert('Por favor escriba el nombre del concepto') 
         event.preventDefault();
       }     
       if ( $("#tipo").val()==0)
       {
         alert('Por favor selecciona si es devengado o deducido el concepto') 
         event.preventDefault();
       }     
       if ( $("#tipo2").val()==0)
       {
         alert('Por favor selecciona si es por valor u horas el concepto') 
         event.preventDefault();
       }    
       if ( $("#idTnomm").val()==null)
       {
         alert('Por favor selecciona la nomina afectada') 
         event.preventDefault();
       }     
       if ( $("#codCta").val()==0)
       {
         alert('Por favor determina la cuenta contable asociada') 
         event.preventDefault();
       }    
          //alert('ya esta casi');
       if ( $("#idTomFon2").val()==0 )
       {
       
          //alert('dsfsff');
          //
          if ( $(".idNitFondos").val()==1 )
           {
              alert('Debe seleccionar un fondo'); 
              event.preventDefault();

        
       
        
           }  

       
          
       }  

    });  

  });




  
 

  
</script>                 


