<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
  <div class="col-sm-4">Empleados:<br />
   <?php
     $select = $form->get('idEmp');
     echo $this->formSelect($select);
     echo $this->formElementErrors($select);
   ?>
  </div> 
  <div class="col-sm-4"><br />
    <?php echo $this->formElement($form->get('registrar')) ?>
  </div> 
</div>
<hr />
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<?php echo $this->form()->closeTag() ?>


<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["id"] ?></td>
            <td><?php echo $dato["CedEmp"] ?></td>                    
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["apellido"] ?></td>
            <td><?php echo $dato["nomGrup"] ?></td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
<?php 
$this->ncol='null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>

<?php echo $this->render('layout/iregresar') ?> 