<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">    
<div class="col-sm-4">Codigo:<br />
<?php
    $name = $form->get('clave1')->setAttributes(array('type'=>'text','class'=>'form-control'));
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>  

</div>    

<hr />
<div class="row">    
<div class="col-sm-2">Hora de inicio:<br />
<?php
    $name = $form->get('hora');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>  
<div class="col-sm-2">Hora de salida:<br />
<?php
    $name = $form->get('hora2');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>    
</div>  
</div>

<hr />
<div class="row">    
<div class="col-sm-2">Horas ordinarias:<br />
<?php
    $name = $form->get('ano');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>  
<div class="col-sm-2">Horas adicionales:<br />
<?php
    $name = $form->get('numero2');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>    
</div>  
<div class="col-sm-2">Horas de recargos:<br />
<?php
    $name = $form->get('valor');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>    
</div>  
</div>

<hr />

<div class="row">    
<div class="col-sm-3">
<?php
    $select = $form->get('check1');
    echo $this->formCheckbox($select);
?><span class="lbl"></span><strong>HORARIO DE DECANSO  </strong>  
</div> 
</div>    


<hr />
<div class="row">    
<div class="col-sm-2">Horas diurnas:<br />
<?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>  
<div class="col-sm-2">Horas nocturnas:<br />
<?php
    $name = $form->get('numero1');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>    
</div>  
<div class="col-sm-3">
<?php
    $select = $form->get('check2');
    echo $this->formCheckbox($select);
?><span class="lbl"></span><strong>HORARIO DE AMANECIDA  </strong>  
</div> 
</div>    

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    