<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">    
  <div class="col-sm-5">Concepto:<br />
      <?php
      $select = $form->get('idConc')->setAttribute("id","idConc");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>     
  <div class="col-sm-3">Dia:<br />
      <?php
      $select = $form->get('tipo')->setAttribute("id","tipo");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>  
  <div class="col-sm-2">Tipo:<br />
      <?php
      $select = $form->get('tipo1')->setAttribute("id","tipo1");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>    
</div>    
   

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    