<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php echo $this->form()->closeTag() ?>
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
<?php 
echo $this->render('layout/titulo') ?>
  <div class="col-sm-2"><br />              
      <?php echo $this->formElement($form->get('buscar')) ?>
  </div>

<div id='resultado'></div>


<script>  
 $(function (){     
     $('#submitbutton').click(function(){ 
       var id = $("#id").val();  
       var parametros = {
            "id"   : id,
       };        
       //alert(id) 
       $.ajax({
             data:  parametros,     
             type:  'post',
             url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>em',
             beforeSend: function () {
                 $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Recalculando por favor espere...');
             },
              success:  function (response) {
                 $("#resultado").html(response);  
                 //   alert("Cuotas registradas de forma correcta")
              }
         }); // Fin ajax                                                                                       

       
     });
 })
</script>   

                  <?php // Parametros para impresion de documento 
                  //if ($por>0)
                  //{
                  //  $this->idR = 1; // Id del reporte
                  //  $this->idP = $this->id.'.'.$dat["idEmp"];
                  //  echo $this->render('layout/ifpdf'); // Fin parametros 
                  //}?>