<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
<div class="col-sm-4">Tipo de labor<br />
<?php
    $select = $form->get('tipo');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>  
<div class="col-sm-4">Unidad de medida<br />
<?php
    $select = $form->get('tipo1');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>      
</div>    
<br />
<div class="row">    
<div class="col-sm-4">Valor de la labor:<br />
<?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
<div class="col-sm-4">Conceptos asociados:<br />
    <?php
      $select = $form->get('idConcM');
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>
</div>
<hr />
<div class="row">    
  <div class="col-sm-10"><br />
    <?php echo ($this->formRow($form->get('formula')));?>
  </div>  
</div>  
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    