<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i/1',
    'method' => 'post',
    'id' => 'formGuardar',
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">    
<div class="col-sm-4">Buscar:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
</div>

<?php echo $this->form()->closeTag() ?>

<hr />

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>

<hr />

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["id"] ?></td>            
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["nomCli"] ?></td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ipersonal');
                 if ( $dato["numE"]>0 )
                 { 
                    echo '('.$dato["numE"].')';  
                 }
                 ?> </a>
            </td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>p/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ifortaleza') ;
                 if ( $dato["numP"]>0 )
                 { 
                    echo '('.$dato["numP"].')';  
                 }
                ?> </a>
            </td>                        
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>   
        
<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Nomina\Model\Entity\Grupos($con)';// Modelo de consulta
$this->funcion   = '$m->getRegistro()';
$this->columnas  = "ID, NOMBRE";// Columnas
$this->datos     = "id,nombre";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/tabla_p') ?>
