<?php
$form = $this->form;
$form->prepare();
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

?>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Puesto</th>  
        <th>Ciudad</th>          
        <th>Sede</th>                  
        <th>Proyecto</th>                  
        <th>Ok</th>                          
    </tr>    
<?php foreach( $this->datos as $dat ){ ?>
  <tr>
    <td><?php echo $dat['nombre']; ?></td>  
    <td><?php echo $dat['nomCiu']; ?></td>      
    <td><?php echo $dat['nomSed']; ?></td>          
    <td><?php echo $dat['nomProy']; ?></td>              
    <td>
        <a href="javascript:editar(<?php echo $dat["id"];?>);"><?php echo $this->render('layout/iok') ?></a>
    </td>                                                
  <tr>        
<?php } ?>
</table>  

<div id="resultadoEr"></div>


<script>  
  // Editar registro  
  function editar(id)
  {
     var idReq    = $("#id").val();
     var idPt    = $("#id2").val();
     var parametros = {
         "idReq"     : idReq,
         "idPt"     : idPt, // n_proyectos_ep 
         "idPues" : id,    
     };
     $.ajax({
        data:  parametros, 
        url:  '<?php echo $this->basePath() ?><?php echo $this->lin?>ptg',
        type: 'post',
        beforeSend: function () {
            $("#resultadoEr").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');            
             },
        success:  function (response) {  
          $("#resultadoEr").html(response);            
             }
        }); // Fin  agregar nuevo componente al sistema                        
        alert("Registro insertado de forma correcta !")
        location.reload();
  }    
 </script>  

